# this file fulfills swagger routing on the /user/{uuid} path
# the operationId is handled through the app loader index.js
# a GET operation that passes in a key value as the last portion of
# a URI will also work here. Note that we are not using the
# database id PK here, this is a design choice to avoid the sin of
# leaking DB PK to the world
delete:
  summary: Deletes a record.
  operationId: deleteSample
  description: DELETE operation by some uuid key
  tags:
    - Sample
  responses:
    "200":
      description: success or failure
      content:
        application/json:
          schema:
            type: object
            properties:
              sampleCode:
                type: string
              name:
                type: string
              message:
                type: string
    default:
      $ref: "../api/responses/server-error.yaml"
